# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Go3IvmxxRGoR4t2kMoOX6CPpmnsOdzs
"""

opção=0
while opção<1:
  print("")
  print("Escolha a operação que deseja fazer:")
  print("1-Adição")
  print("2-Subtração")
  print("3-Multiplicação")
  print("4-Divisão")
  print("5-Potenciação")
  print("6-Resto")
  print("")
  operação=int(input("Digite qual a operação que deseja escolher: "))
  if(operação == 1):
    numero1 = float(input("Digite um numero: \n"))
    numero2 = float(input("Digite outro numero: \n"))
    resultado = numero1 + numero2
    print("O resultado da adição é: ", resultado)
  if(operação == 2):
    numero1 = float(input("Digite um numero: \n"))
    numero2 = float(input("Digite outro numero: \n"))
    resultado = numero1 - numero25
    print("O resultado da subtração é: ", resultado)
  if(operação == 3):
    numero1 = float(input("Digite um numero: \n"))
    numero2 = float(input("Digite outro numero: \n"))
    resultado = numero1 * numero2
    print("O resultado da multiplicação é: ",resultado)
  if(operação == 4):
    numero1 = float(input("Digite um numero: \n"))
    numero2 = float(input("Digite outro numero: \n"))
    resultado = numero1 / numero2
    print("O resultado da divisão é: ",resultado)
  if(operação == 5):
    numero1 = float(input("Digite um numero: \n"))
    numero2 = float(input("Digite outro numero: \n"))
    resultado = numero1 ** numero2
    print("O resultado da potenciação é: ",resultado)
  if(operação == 6):
    numero1 = float(input("Digite um numero: \n"))
    numero2 = float(input("Digite outro numero: \n"))
    resultado = numero1 % numero2
    print("O resultado em resto é: ",resultado)

  print("")
  print("Deseja realizar outra operação?")
  opção=int(input("Digite 0 para SIM ou 1 para NÃO = "))